### ISSUE TITLE
Upgrade to Laravel 8

### ISSUE THREAD

**Issue by NoelDeMartin** [NoelDeMartin/laravel-cypress-sandbox#2]
The [0.2.1 release](https://github.com/NoelDeMartin/laravel-cypress/releases/tag/v0.2.1) release of laravel-cypress added support for Laravel 8 factories, it'd be nice to upgrade this project to Laravel 8 using the new factories. This is for the most part an out-of-the-box Laravel project, so it should be easy for any Laravel developer.

Instructions to upgrade a Laravel application can be found in the official [Upgrade Guide](https://laravel.com/docs/8.x/upgrade).

**Comment by JunaidJaved248** [comment]
@NoelDeMartin Assign it to me!!
I am laravel Developer, And I am on it (Upgrading your Project)

**Comment by NoelDeMartin** [comment]
Hi there @JunaidJaved248, I see there are two PRs open but I'll merge yours because you asked first. I've removed the label to avoid confusions.

@DevRPL please, always look at the repo and issue before submitting a PR. Specially during hacktoberfest. I'm sorry to have wasted your time.

**Comment by NoelDeMartin** [comment]
Solved in #5
